```{r}
library(caret)
library(rpart)
library(randomForest)
library(rpart.plot)
library(rattle)
library(RColorBrewer)
set.seed(1997)
```

```{r}
trainSp <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testSp <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
```

```{r}
trainingS <- read.csv(url(trainSp), na.strings=c("NA","#DIV/0!",""))
testingS <- read.csv(url(testSp), na.strings=c("NA","#DIV/0!",""))
```

```{r}
trainingS <- read.csv(url(trainSp), na.strings=c("NA","#DIV/0!",""))
testingS <- read.csv(url(testSp), na.strings=c("NA","#DIV/0!",""))
indTrainS <- createDataPartition(y=trainingS$classe, p=0.6, list=FALSE)
myTrainingS <- trainingS[indTrainS, ]; myTestingS <- trainingS[-indTrainS, ]
dim(myTrainingS); dim(myTestingS)
```
        
```{r}
DataNZV <- nearZeroVar(myTrainingS, saveMetrics=TRUE)
NZV <- names(myTrainingS) %in% c("new_window", "kurtosis_roll_belt", "kurtosis_picth_belt",
"kurtosis_yaw_belt", "skewness_roll_belt", "skewness_roll_belt.1", "skewness_yaw_belt",
"max_yaw_belt", "min_yaw_belt", "amplitude_yaw_belt", "avg_roll_arm", "stddev_roll_arm",
"var_roll_arm", "avg_pitch_arm", "stddev_pitch_arm", "var_pitch_arm", "avg_yaw_arm",
"stddev_yaw_arm", "var_yaw_arm", "kurtosis_roll_arm", "kurtosis_picth_arm",
"kurtosis_yaw_arm", "skewness_roll_arm", "skewness_pitch_arm", "skewness_yaw_arm",
"max_roll_arm", "min_roll_arm", "min_pitch_arm", "amplitude_roll_arm", "amplitude_pitch_arm",
"kurtosis_roll_dumbbell", "kurtosis_picth_dumbbell", "kurtosis_yaw_dumbbell", "skewness_roll_dumbbell",
"skewness_pitch_dumbbell", "skewness_yaw_dumbbell", "max_yaw_dumbbell", "min_yaw_dumbbell",
"amplitude_yaw_dumbbell", "kurtosis_roll_forearm", "kurtosis_picth_forearm", "kurtosis_yaw_forearm",
"skewness_roll_forearm", "skewness_pitch_forearm", "skewness_yaw_forearm", "max_roll_forearm",
"max_yaw_forearm", "min_roll_forearm", "min_yaw_forearm", "amplitude_roll_forearm",
"amplitude_yaw_forearm", "avg_roll_forearm", "stddev_roll_forearm", "var_roll_forearm",
"avg_pitch_forearm", "stddev_pitch_forearm", "var_pitch_forearm", "avg_yaw_forearm",
"stddev_yaw_forearm", "var_yaw_forearm")
myTrainingS <- myTrainingS[!NZV]

dim(myTrainingS)
```

```{r}
myTrainingS <- myTrainingS[c(-1)]
training3 <- myTrainingS 
for(i in 1:length(myTrainingS)) {
        if( sum( is.na( myTrainingS[, i] ) ) /nrow(myTrainingS) >= .6 ) { 
        for(j in 1:length(training3)) {
            if( length( grep(names(myTrainingS[i]), names(training3)[j]) ) ==1) { 
                training3 <- training3[ , -j] 
            }   
        } 
    }
}
dim(training3)
```

```{r}
myTrainingS <- training3
rm(training3)
```

```{r}
clean1 <- colnames(myTrainingS)
clean2 <- colnames(myTrainingS[, -58]) 
myTestingS <- myTestingS[clean1]
testingS <- testingS[clean2]
dim(myTestingS)
dim(testingS)
```

```{r}
for (i in 1:length(testingS) ) {
        for(j in 1:length(myTrainingS)) {
        if( length( grep(names(myTrainingS[i]), names(testingS)[j]) ) ==1)  {
            class(testingS[j]) <- class(myTrainingS[i])
        }      
    }      
}
testingS <- rbind(myTrainingS[2, -58] , testingS) 
testingS <- testingS[-1,]
```

```{r}
modFit1 <- rpart(classe ~ ., data=myTrainingS, method="class")
fancyRpartPlot(modFit1)
```

```{r}
predictions1 <- predict(modFit1, myTestingS, type = "class")
```


```{r}
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}
pml_write_files(predictions1)
```

